
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace climatemonitorem
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.Ethernet_J11D ethernet;
        Gadgeteer.Modules.GHIElectronics.Display_T35 display;
        Gadgeteer.Modules.Seeed.CellularRadio cellularRadio;
        Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        Gadgeteer.Modules.GHIElectronics.LightSensor lightsense;
        Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        Gadgeteer.Modules.GHIElectronics.MulticolorLed led;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
		
            cellularRadio = new GTM.Seeed.CellularRadio(4);
		
            ethernet = new GTM.GHIElectronics.Ethernet_J11D(7);
		
            led = new GTM.GHIElectronics.MulticolorLed(8);
		
            lightsense = new GTM.GHIElectronics.LightSensor(9);
		
            temperatureHumidity = new GTM.Seeed.TemperatureHumidity(11);
		
            display = new GTM.GHIElectronics.Display_T35(14, 13, 12, Socket.Unused);

        }
    }
}
